### ISSUE TITLE
CDC Mental Health Extraction

### ISSUE THREAD

**Issue by sryan9** [brownhr/AppHumanGHY#3]
- [ ] Decide which MH outcomes to look at
- [x] Extract in R
- [x] Create new CSV
- [x] Extract solely WNC counties/affiliated ZCTAs

**Comment by brownhr** [comment]
# TODO

## PLACES dataset manipulation

- [ ] Choose factors from `MeasureID`
  - Total population (not Population!)
- [ ] Recode `MeasureId` column
  - Factors:
  - [ ] 
- [x] Single row for each ZCTA

**Comment by brownhr** [comment]
Added the `places_wnc_zcta.shp` to the `data/shp` folder.

Load it in using `sf::st_read()` so it keeps geometry
